package example.cli;

import java.util.Map;
import javax.xml.ws.*;
import static javax.xml.ws.BindingProvider.ENDPOINT_ADDRESS_PROPERTY;

import example.ws.*; // classes generated by wsimport from WSDL


public class HelloClient {

    public static void main(String[] args) {
        HelloImplService service = new HelloImplService();
        Hello port = service.getHelloImplPort();

        BindingProvider bindingProvider = (BindingProvider) port;
        Map<String, Object> requestContext = bindingProvider.getRequestContext();

        if (args.length < 1) {
            // get endpoint address
            Object url = requestContext.get(ENDPOINT_ADDRESS_PROPERTY);
            System.out.printf("Remote call to %s ...%n", url);

            // call using default endpoint address
            String result = port.sayHello("friend");
            System.out.println(result);
        } else {
            // set endpoint address
            String url = args[0];
            requestContext.put(ENDPOINT_ADDRESS_PROPERTY, url);
            System.out.printf("Remote call to %s ...%n", url);

            // call using set endpoint address
            String result = port.sayHello("friend");
            System.out.println(result);
        }

    }

}
