package example.ws.test;

import org.junit.*;
import static org.junit.Assert.*;

import javax.xml.soap.*;

import example.ws.cli.*;
import calc.*; // classes generated by wsimport from WSDL


/**
 *  Super class for test suites
 */
public abstract class AbstractCalcTest {

    // static members

    protected static CalcClient client;


    // one-time initialization and clean-up

    @BeforeClass
    public static void oneTimeSetUp() throws CalcClientException {
        client = new CalcClient();
    }

    @AfterClass
    public static void oneTimeTearDown() {
        client = null;
    }

    // initialization and clean-up for each test

    @Before
    public void setUp() throws SOAPException {
        sendReset();
    }

    @After
    public void tearDown() {
    }


    protected static void sendReset() throws SOAPException {
        sendReset(client.getEndpointAddress() + "/test");
    }

    protected static void sendReset(String endpointAddress) throws SOAPException {
        // initialize SAAJ
        SOAPConnectionFactory soapConnectionFactory = SOAPConnectionFactory.newInstance();
        MessageFactory messageFactory = MessageFactory.newInstance();

        // create SOAP message
        SOAPMessage soapMessage = messageFactory.createMessage();

        // access SOAP envelope
        SOAPPart soapPart = soapMessage.getSOAPPart();
        SOAPEnvelope soapEnvelope = soapPart.getEnvelope();

        // access SOAP body
        SOAPBody soapBody = soapEnvelope.getBody();

        // create new SOAP body element
        Name name = soapEnvelope.createName("reset", "", "urn:pt:ulisboa:tecnico:ws:test");
        soapBody.addChildElement(name);

        // SOAP call
        SOAPConnection soapConnection = null;
        try {
            // create connection
            soapConnection = soapConnectionFactory.createConnection();
            // call
            soapConnection.call(soapMessage, endpointAddress);
        } finally {
            soapConnection.close();
        }
    }

}
