package example.ws.test;

import org.junit.*;
import static org.junit.Assert.*;

import calc.*; // classes generated by wsimport from WSDL


/**
 *  Test suite
 */
public class IntDivTest extends AbstractCalcTest {

    // tests
    // assertEquals(expected, actual);

//      public int intdiv(int a, int b) throws DivideByZero

    @Test(expected=DivideByZero.class)
    public void testDivideByZero() throws Exception {
        client.intdiv(13, 0);
        // JUnit expects the exception declared in the annotation
    }

    @Test
    public void testExact() throws Exception {
        final int result = client.intdiv(10, 5);
        assertEquals(2, result);
    }

    @Test
    public void testRound() throws Exception {
        final int result = client.intdiv(10, 4);
        assertEquals(2, result);
    }

    @Test
    public void testExactNegative() throws Exception {
        final int result = client.intdiv(-10, -5);
        assertEquals(2, result);
    }

    @Test
    public void testRoundNegative() throws Exception {
        final int result = client.intdiv(-10, -4);
        assertEquals(2, result);
    }

    // ...

}
