package example.ws.test;

import org.junit.*;
import static org.junit.Assert.*;

import example.ws.cli.*;
import calc.*; // classes generated by wsimport from WSDL


/**
 *  Super class for test suites
 */
public abstract class AbstractCalcTest {

    // static members

    protected static CalcClient client;


    // one-time initialization and clean-up

    @BeforeClass
    public static void oneTimeSetUp() throws CalcClientException {
        client = new CalcClient();
    }

    @AfterClass
    public static void oneTimeTearDown() {
        client = null;
    }

}
